version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: trucktools-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 592802
      MYSQL_DATABASE: truckTools
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
      - ./TruckToolsBackend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: trucktools-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:

